/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 */

'use strict';

import testFixtures from '../testFixtures';

// Copied all the tests with something like this: (had to create directories first though)
// find ~/dev/babel/packages/babel-generator/test/fixtures -name "actual.js" -exec bash -c 'cp "$1" $(echo "$1" | sed "s/\/actual//g" | sed -E "s/\/.*\/(.*)\//.\/\\1\//g")' -- {} \;
testFixtures('babel', new Set([
  'jsx.js',
  'do-while-line-comment.js',
  'function-block-line-comment.js',
  'return-no-argument.js',
  'try-block-line-comment.js',
  'while.js',
  'for-in-no-in.js',
  'for-loop-in.js',
  'new-precedence.js',
  'one-property-with-line-terminator.js',
  'unary-op.js',
  'variable-declaration.js',
  'array-types.js',
  'call-properties.js',
  'declare-module.js',
  'declare-statements.js',
  'def-site-variance.js',
  'interfaces-module-and-script.js',
  'null-literal-types.js',
  'qualified-generic-type.js',
  'type-alias.js',
  'type-annotations.js',
  'type-parameters.js',
  'typecasts.js',
  'arrow-function.js',
  'class-expression.js',
  'computed-property.js',
  'default-parameter.js',
  'destructuring-assignment.js',
  'exports.js',
  'for-of-statement.js',
  'import-with-default.js',
  'imports.js',
  'spread-element.js',
  'templates-escape.js',
  'templates-indentation.js',
  'templates.js',
  'yield-precedence.js',
  'arrow-functions.js',
  'new-expression.js',
  'no-semicolon.js',
  'arrow-function-object-body.js',
  'arrow-function.js',
  'await-expression.js',
  'expression.js',
  'sequence-expressions.js',
  'unary-arrow-function.js',
  'yield-expression.js',
  'ArrowFunctionExpression.js',
  'AwaitExpression.js',
  'BindExpression.js',
  'BreakStatement.js',
  'ClassBody-MethodDefinition.js',
  'ClassDeclaration.js',
  'ClassExpression.js',
  'ContinueStatement.js',
  'Decorator.js',
  'DoWhileStatement.js',
  'ExportDefaultDeclaration-ExportSpecifier-ExportNamedDeclaration.js',
  'ForInStatement.js',
  'ForOfStatement.js',
  'ForStatement.js',
  'FunctionDeclaration-FunctionExpression.js',
  'ImportDeclaration-ImportSpecifier-ImportNamespaceSpecifier.js',
  'LabeledStatement.js',
  'NewExpression.js',
  'ObjectExpression-ObjectPattern-Property.js',
  'ReturnStatement.js',
  'SequenceExpression.js',
  'SpreadElement-SpreadProperty.js',
  'SwitchStatement-SwitchCase.js',
  'TemplateLiteral-TaggedTemplateExpression-TemplateElement.js',
  'ThrowStatement.js',
  'TryStatement-CatchClause.js',
  'UnaryExpression.js',
  'VariableDeclaration-VariableDeclarator.js',
  'WhileStatement.js',
  'WithStatement.js',
  'YieldExpression.js',
]));
